[package]
name = "yandex_translate_async"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]

[dependencies]
hyper = "0.11.25"
tokio-core = "0.1.17"
hyper-tls = "0.1.3"
serde_json = "1.0.17"
serde = "1.0.45"
serde_derive = "1.0.45"
futures = "0.1"
serde_urlencoded = "0.5.1"
